#!/bin/bash
OSP_GUID="fbc1"
TOWER_GUID="9de6"
OPENTLC_LOGIN="porfirio.agustin-atos.net"
GITHUB_REPO="https://github.com/elmaco1979/ansible_advance_homework"
JQ_REPO_BASE="http://www.opentlc.com/download/ansible_bootcamp"
REGION="us-east-1"
RH_MAIL_ID="porfirio.agustin"
ANSIBLE_ADVANCE_GUID="4347"